export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARDS = 'DELETE_CARDS';
export const TOGGLE_CARD = 'TOGGLE_CARD';
export const SAVE_CHANGES = 'SAVE_CHANGES';
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const VIEW_MODE_HANDLER = 'VIEW_MODE_HANDLER'
